name: todo_mini
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  fake_cloud_firestore: ^4.0.1
  firebase_auth_mocks: ^0.15.1

flutter:

  uses-material-design: true
